"""
HTML & CSS Overview - Examples
==============================
Demonstrates generating HTML content with Python.
"""

print("=" * 60)
print("HTML & CSS OVERVIEW - Examples")
print("=" * 60)

# =============================================================================
# SECTION 1: Generating Basic HTML with Python
# =============================================================================
print("\n--- 1: Generating Basic HTML ---\n")

def generate_basic_page(title, content):
    """Generate a simple HTML page."""
    html = f"""<!DOCTYPE html>
<html>
<head>
    <title>{title}</title>
</head>
<body>
    <h1>{title}</h1>
    <p>{content}</p>
</body>
</html>"""
    return html

page = generate_basic_page("My Page", "Welcome to my website!")
print("Generated HTML:")
print(page)

# =============================================================================
# SECTION 2: Building HTML Elements Programmatically
# =============================================================================
print("\n--- 2: Building HTML Elements ---\n")

def make_tag(name, content, **attrs):
    """Create an HTML tag with attributes."""
    attr_str = ""
    for key, value in attrs.items():
        attr_str += f' {key}="{value}"'
    return f"<{name}{attr_str}>{content}</{name}>"

# Create elements
heading = make_tag("h1", "Hello World", class_="main-title")
paragraph = make_tag("p", "This is a paragraph with a ", class_="text")
link = make_tag("a", "link", href="https://example.com", target="_blank")

print(f"Heading: {heading}")
print(f"Paragraph: {paragraph}")
print(f"Link: {link}")

# =============================================================================
# SECTION 3: Generating Lists from Python Data
# =============================================================================
print("\n--- 3: Generating Lists from Data ---\n")

def generate_list(items, ordered=False):
    """Generate HTML list from Python list."""
    tag = "ol" if ordered else "ul"
    items_html = "\n".join(f"        <li>{item}</li>" for item in items)
    return f"""<{tag}>
{items_html}
    </{tag}>"""

fruits = ["Apple", "Banana", "Cherry", "Date"]
print("Unordered List:")
print(generate_list(fruits))

steps = ["Preheat oven", "Mix ingredients", "Bake for 30 min"]
print("\nOrdered List:")
print(generate_list(steps, ordered=True))

# =============================================================================
# SECTION 4: Generating Tables from Data
# =============================================================================
print("\n--- 4: Generating Tables from Data ---\n")

def generate_table(headers, rows):
    """Generate HTML table from Python data."""
    header_html = "".join(f"<th>{h}</th>" for h in headers)
    rows_html = ""
    for row in rows:
        row_cells = "".join(f"<td>{cell}</td>" for cell in row)
        rows_html += f"        <tr>{row_cells}</tr>\n"
    
    return f"""<table border="1">
    <thead>
        <tr>{header_html}</tr>
    </thead>
    <tbody>
{rows_html}    </tbody>
</table>"""

headers = ["Name", "Age", "City"]
people = [
    ["Alice", "25", "New York"],
    ["Bob", "30", "London"],
    ["Carol", "28", "Tokyo"]
]

print(generate_table(headers, people))

# =============================================================================
# SECTION 5: Adding CSS Styles
# =============================================================================
print("\n--- 5: Adding CSS Styles ---\n")

def generate_styled_page(title, content):
    """Generate an HTML page with embedded CSS."""
    return f"""<!DOCTYPE html>
<html>
<head>
    <title>{title}</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            max-width: 800px;
            margin: 40px auto;
            padding: 20px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: #333;
        }}
        .container {{
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 10px 30px rgba(0,0,0,0.3);
        }}
        h1 {{
            color: #667eea;
            border-bottom: 3px solid #667eea;
            padding-bottom: 10px;
        }}
        .highlight {{
            background: #fff3cd;
            padding: 2px 6px;
            border-radius: 4px;
        }}
        footer {{
            text-align: center;
            margin-top: 30px;
            color: #666;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <div class="container">
        <h1>{title}</h1>
        <p>{content}</p>
        <p>This page has <span class="highlight">beautiful styling</span> generated by Python!</p>
        <footer>Generated with Python {__import__('sys').version[:5]}</footer>
    </div>
</body>
</html>"""

styled_page = generate_styled_page(
    "Styled Page Demo",
    "This page demonstrates inline CSS styling."
)
print("Styled page HTML generated (preview first 500 chars):")
print(styled_page[:500] + "...")

# =============================================================================
# SECTION 6: Navigation Component
# =============================================================================
print("\n--- 6: Navigation Component ---\n")

def generate_nav(items, active=None):
    """Generate a navigation menu."""
    links = []
    for name, url in items:
        class_attr = ' class="active"' if name == active else ""
        links.append(f'        <li><a href="{url}"{class_attr}>{name}</a></li>')
    
    links_html = "\n".join(links)
    
    return f"""<nav>
    <ul>
{links_html}
    </ul>
</nav>
<style>
    nav ul {{
        list-style: none;
        padding: 0;
        display: flex;
        gap: 20px;
        background: #333;
        padding: 15px;
    }}
    nav a {{
        color: white;
        text-decoration: none;
        padding: 5px 15px;
        border-radius: 4px;
        transition: background 0.3s;
    }}
    nav a:hover {{
        background: #555;
    }}
    nav a.active {{
        background: #007bff;
    }}
</style>"""

nav_items = [
    ("Home", "/"),
    ("About", "/about"),
    ("Services", "/services"),
    ("Contact", "/contact")
]

print(generate_nav(nav_items, active="Home"))

# =============================================================================
# SECTION 7: Card Component
# =============================================================================
print("\n--- 7: Card Component ---\n")

def generate_card(title, description, footer=None):
    """Generate a card component."""
    footer_html = f'<div class="card-footer">{footer}</div>' if footer else ""
    return f"""<div class="card">
    <div class="card-header">
        <h3>{title}</h3>
    </div>
    <div class="card-body">
        <p>{description}</p>
    </div>
    {footer_html}
</div>
<style>
    .card {{
        border: 1px solid #ddd;
        border-radius: 8px;
        overflow: hidden;
        max-width: 300px;
        box-shadow: 0 2px 8px rgba(0,0,0,0.1);
    }}
    .card-header {{
        background: #f8f9fa;
        padding: 15px;
        border-bottom: 1px solid #ddd;
    }}
    .card-header h3 {{
        margin: 0;
        color: #333;
    }}
    .card-body {{
        padding: 15px;
    }}
    .card-footer {{
        padding: 10px 15px;
        background: #f8f9fa;
        border-top: 1px solid #ddd;
        font-size: 0.9em;
        color: #666;
    }}
</style>"""

print(generate_card(
    "Python Basics",
    "Learn the fundamentals of Python programming.",
    "Duration: 4 weeks"
))

# =============================================================================
# SECTION 8: Complete Page Builder
# =============================================================================
print("\n--- 8: Complete Page Builder ---\n")

class PageBuilder:
    """Build complete HTML pages programmatically."""
    
    def __init__(self, title):
        self.title = title
        self.sections = []
    
    def add_section(self, heading, content):
        self.sections.append((heading, content))
    
    def build(self):
        sections_html = ""
        for heading, content in self.sections:
            sections_html += f"""
        <section>
            <h2>{heading}</h2>
            <p>{content}</p>
        </section>"""
        
        return f"""<!DOCTYPE html>
<html>
<head>
    <title>{self.title}</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, sans-serif;
            line-height: 1.6;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }}
        h1 {{
            color: #2c3e50;
            text-align: center;
        }}
        section {{
            background: #f8f9fa;
            padding: 20px;
            margin: 20px 0;
            border-radius: 8px;
            border-left: 4px solid #3498db;
        }}
        h2 {{
            color: #3498db;
            margin-top: 0;
        }}
    </style>
</head>
<body>
    <h1>{self.title}</h1>
    {sections_html}
</body>
</html>"""

# Build a page
builder = PageBuilder("My Learning Journey")
builder.add_section("Getting Started", "I began learning Python basics.")
builder.add_section("First Project", "Built a calculator application.")
builder.add_section("Next Steps", "Planning to learn web development.")

complete_page = builder.build()
print("Complete page HTML generated!")
print(f"Total length: {len(complete_page)} characters")

# =============================================================================
# SECTION 9: Writing HTML to File
# =============================================================================
print("\n--- 9: Writing HTML to File ---\n")

# Create a sample HTML file
sample_html = generate_styled_page(
    "Sample Page",
    "This HTML file was generated by Python!"
)

try:
    with open("sample_page.html", "w", encoding="utf-8") as f:
        f.write(sample_html)
    print("Created 'sample_page.html' - open it in a browser!")
    print("(File will be cleaned up at the end)")
except IOError as e:
    print(f"Could not write file: {e}")

# =============================================================================
# SECTION 10: CSS Utility Classes Generator
# =============================================================================
print("\n--- 10: CSS Utility Classes ---\n")

def generate_utility_css():
    """Generate common utility CSS classes."""
    utilities = {
        "text-center": "text-align: center;",
        "text-left": "text-align: left;",
        "text-right": "text-align: right;",
        "bold": "font-weight: bold;",
        "italic": "font-style: italic;",
        "underline": "text-decoration: underline;",
        "m-1": "margin: 0.25rem;",
        "m-2": "margin: 0.5rem;",
        "m-3": "margin: 1rem;",
        "p-1": "padding: 0.25rem;",
        "p-2": "padding: 0.5rem;",
        "p-3": "padding: 1rem;",
        "hidden": "display: none;",
        "block": "display: block;",
        "inline": "display: inline;",
        "flex": "display: flex;",
        "rounded": "border-radius: 4px;",
        "shadow": "box-shadow: 0 2px 4px rgba(0,0,0,0.1);"
    }
    
    css_lines = ["/* Utility Classes */"]
    for name, rule in utilities.items():
        css_lines.append(f".{name} {{ {rule} }}")
    
    return "\n".join(css_lines)

print(generate_utility_css())

# Cleanup
import os
try:
    if os.path.exists("sample_page.html"):
        os.remove("sample_page.html")
        print("\n(Cleaned up sample_page.html)")
except:
    pass

print("\n" + "=" * 60)
print("Examples complete! Try exercises.py next.")
print("=" * 60)
